[package]
name = "deps-example"
version = "0.1.0"
authors = ["Justin A Ryan <justizin@justiz.in>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.0"
